CREATE TABLE llx_type_relations (
    rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
    -- BEGIN MODULEBUILDER FIELDS
    name VARCHAR(255) NOT NULL DEFAULT ""
    -- END MODULEBUILDER FIELDS
) ENGINE=innodb